export default [
  {
    id: 1,
    title: "The Mandalorian",
    year: 2019,
    director: "Jon Favreau",
    duration: "40min",
    genre: ["Action", "Adventure", "Fantasy"],
    rate: 8.8,
    img: "https://i.ibb.co/R3pR042/mandalorian.jpg",
    banner: "https://i.ibb.co/R3pR042/mandalorian.jpg",
    description:
      "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
    like: false,
  },
  {
    id: 2,
    title: "The Witcher",
    year: 2019,
    director: "Lauren Schmidt",
    duration: "1h",
    genre: ["Action", "Adventure", "Drama"],
    rate: 8.2,
    img: "https://i.ibb.co/RyzQWnK/whitcher.jpg",
    banner: "https://i.ibb.co/RyzQWnK/whitcher.jpg",
    description:
      "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    like: false,
  },
  {
    id: 3,
    title: "Game of Thrones",
    year: 2011,
    director: "David Benioff",
    duration: "57min",
    genre: ["Action", "Adventure", "Drama"],
    rate: 9.3,
    img: "https://i.ibb.co/bgWSsfq/got.jpg",
    banner: "https://i.ibb.co/bgWSsfq/got.jpg",
    description:
      "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    like: false,
  },
  {
    id: 4,
    title: "Breaking Bad",
    year: 2008,
    director: "Vince Gilligan",
    duration: "49min",
    genre: ["Crime", "Drama", "Thriller"],
    rate: 9.4,
    img: "https://i.ibb.co/r08MwPX/breakingbad.jpg",
    banner: "https://i.ibb.co/r08MwPX/breakingbad.jpg",
    description:
      "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
    like: false,
  },
  {
    id: 5,
    title: "The Queen's Gambit",
    year: 2020,
    director: "Scott Frank",
    duration: "7h",
    genre: ["Drama"],
    rate: 8.6,
    img: "https://i.ibb.co/jhJTsqB/queen.jpg",
    banner: "https://i.ibb.co/jhJTsqB/queen.jpg",
    description:
      "Orphaned at the tender age of nine, prodigious introvert Beth Harmon discovers and masters the game of chess in 1960s USA. But child stardom comes at a price.",
    like: false,
  },
];
